// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Hive5;

namespace Hive5
{
	public enum ObjectFieldType
	{
		None = 0,
		Null = 1,
		Long = 2,
		Double = 3,
		String = 4,
		List = 5,
		Bool = 6,
	};

	public abstract class ObjectField
	{
		public string Key { get; set; }
		public ObjectFieldType FieldType { get; set; }

		public ObjectField ()
		{
			this.FieldType = ObjectFieldType.None;
		}
	}
}

