// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Hive5
{
	public static class Hive5Config
	{
        public static string Host	= "your_prod_server_domain";
		public static string AppKey = "your_app_key"; 
        public static string HealthCheckUrl = "your-health-check-url";
        /// <summary>
        /// Optional
        /// </summary>
		public static string XPlatformKey 	= ""; 

        /// <summary>
        /// Optional
        /// </summary>
		public static string CustomAccountPlatformName = ""; 

        /// <summary>
        /// 중복호출로 단정하지 않는 시간 차이
        /// 순수 서버프로시저 수행 타임아웃 + Http request/response에 대한 latency고려된 값(단위:ms)
        /// </summary>
        public static int DuplicationApiCallExpirationPeriod = 2500;

        /// <summary>
        /// 헬스체크 자동업데이트 주기 (단위: ms)
        /// </summary>
        public static int AutoHealthCheckInterval = 3000000;
    }
}

