// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Hive5
{
	public static class Hive5Config
	{
		public static string AppKey 		= "a40e4122-99d9-44a6-b916-68ed756f79d6"; // Sample game
		public static string XPlatformKey 	= ""; // If you need it, request us 
		public static string CustomAccountPlatformName = ""; 
	}
}

